# Generated by Django 2.1.5 on 2019-01-31 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20190126_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='book.Page', verbose_name='Страница'),
        ),
    ]
